<<<<<<< HEAD
[project]
name = "pyenvdoctor"
version = "0.1.0"
description = "A tool to diagnose and fix pyenv issues"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
    "rich>=13.0.0",
    "inquirer>=3.0.0",
    "packaging>=20.9",
    "requests>=2.31.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "flake8>=5.0.0",
    "mypy>=0.991",
]

[project.scripts]
pyenvdoctor = "pyenvdoctor.cli.commands:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --cov=src/pyenvdoctor --cov-report=term-missing"

[tool.coverage.run]
source = ["src"]
branch = true

[tool.black]
line-length = 100
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
strict = true
=======
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyenvdoctor"
version = "0.1.0"
dependencies = [
    "rich>=13.0.0",
    "inquirer>=3.0.0"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-mock>=3.0.0"
]
>>>>>>> 3eda700a8f77bd07a3cb904af0dfdbd7ab51acd1
